"""Project-wide constants for NetCourier."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_GATEWAY_HOST = "127.0.0.1"
DEFAULT_GATEWAY_CLIENT_PORT = 9000
DEFAULT_GATEWAY_BACKEND_PORT = 9001
DEFAULT_SERVER_S1_PORT = 9101
DEFAULT_SERVER_S2_PORT = 9102

DEFAULT_DB_PATH = PROJECT_ROOT / "data" / "netcourier.db"
DEFAULT_LOG_DIR = PROJECT_ROOT / "logs"

TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"
REQUEST_ID_PREFIX = "REQ"
EVENT_ID_PREFIX = "EVT"

HEADER_LENGTH_BYTES = 4
MAX_HEADER_SIZE = 1024 * 1024
DEFAULT_CHUNK_SIZE = 64 * 1024
MAX_FILE_SIZE = 100 * 1024 * 1024

MESSAGE_TYPES = {
    "REGISTER",
    "REGISTER_OK",
    "LOGIN",
    "LOGIN_OK",
    "LOGOUT",
    "LOGOUT_OK",
    "LIST_ONLINE_USERS",
    "ONLINE_USERS_RESPONSE",
    "PRIVATE_MESSAGE_SEND",
    "PRIVATE_MESSAGE_RECEIVED",
    "PRIVATE_MESSAGE_STATUS",
    "PM_HISTORY_REQUEST",
    "PM_HISTORY_RESPONSE",
    "LIST_ROOMS",
    "ROOM_LIST_RESPONSE",
    "CREATE_ROOM",
    "ROOM_ASSIGNED",
    "JOIN_ROOM",
    "ROOM_LOCATION",
    "REGISTER_BACKEND",
    "BACKEND_REGISTERED",
    "HEARTBEAT",
    "HEARTBEAT_ACK",
    "VALIDATE_TOKEN",
    "TOKEN_VALID",
    "TOKEN_INVALID",
    "USER_ROOM_STATUS_UPDATE",
    "ROOM_STATS_UPDATE",
    "BACKEND_SHUTDOWN",
    "AUTH_BACKEND",
    "AUTH_BACKEND_OK",
    "JOIN_ROOM_BACKEND",
    "JOIN_ROOM_OK",
    "LEAVE_ROOM",
    "LEAVE_ROOM_OK",
    "ROOM_CHAT_SEND",
    "ROOM_CHAT_BROADCAST",
    "ROOM_MESSAGE_REACTION",
    "ROOM_REACTION_BROADCAST",
    "ROOM_HISTORY_REQUEST",
    "ROOM_HISTORY_RESPONSE",
    "ROOM_KICK_USER",
    "ROOM_DELETE_FILE",
    "ROOM_MEMBER_LIST_REQUEST",
    "ROOM_MEMBER_LIST_RESPONSE",
    "ROOM_TYPING_INDICATOR",
    "ROOM_TYPING_BROADCAST",
    "TRANSFER_QUEUE_STATUS",
    "FILE_LIST_REQUEST",
    "FILE_LIST_RESPONSE",
    "UPLOAD_INIT",
    "UPLOAD_READY",
    "UPLOAD_CHUNK",
    "CHUNK_ACK",
    "UPLOAD_FINISH",
    "UPLOAD_SUCCESS",
    "DOWNLOAD_REQUEST",
    "DOWNLOAD_READY",
    "DOWNLOAD_CHUNK",
    "DOWNLOAD_FINISH",
    "RESUME_TRANSFER",
    "TRANSFER_STATUS",
    "SYSTEM_EVENT",
    "PING",
    "PONG",
    "ERROR",
}
